- name: Assert that required vars are defined
  assert:
    that:
      - docker_container is defined

- name: Debug docker_container
  debug:
    var: docker_container

- name: Set boolean variable blue_green_deploy based on docker_container.blue_green_deploy
  set_fact:
    blue_green_deploy: "{{ docker_container.blue_green_deploy | default(true) | bool }}"

- name: When blue_green_deploy is defined and false, include docker_container task
  ansible.builtin.include_tasks: tasks/docker_container_deploy.yml
  vars:
    item: "{{ docker_container }}"
  when: blue_green_deploy == false

- name: When blue_green_deploy is defined and true, include docker_container_blue_green_deploy task
  ansible.builtin.include_tasks: tasks/docker_container_blue_green_deploy.yml
  when: blue_green_deploy == true
