all:
  vars:
    required_docker_label: "org.codekaizen.application=codekaizen-website"
    ansible_user: ansible
    build_number: "{{ ansible_date_time.iso8601_micro | to_uuid }}"
    docker_networks: []
    docker_volumes: []
    docker_containers:
      - name: "codekaizen-website-wordpress"
        image: "alpine:latest"
        labels:
          org.codekaizen.application: "codekaizen-website"
          org.codekaizen.service: "wordpress"
          org.codekaizen.build_number: "{{ build_number }}"
        command: "sleep infinity"
        restart_policy: "always"
        replica_count: 3
        filters_string: '--filter "label=org.codekaizen.application=codekaizen-website" --filter "label=org.codekaizen.service=wordpress"'
      - name: "codekaizen-website-db"
        image: "alpine:latest"
        labels:
          org.codekaizen.application: "codekaizen-website"
          org.codekaizen.service: "db"
          # org.codekaizen.build_number: "{{ build_number }}" # will force a recreate
        command: "sleep infinity"
        restart_policy: "always"
        replica_count: 2
        filters_string: '--filter "label=org.codekaizen.application=codekaizen-website" --filter "label=org.codekaizen.service=db"'
        blue_green_deploy: false
        comparisons:
          "*": ignore # by default, ignore *all* options (including image)
          image: strict
          networks: strict
          volumes: strict
          env: strict # except for environment variables; there, we want to be strict
          restart_policy: strict
          labels: strict # will force a recreate

  hosts:
    9c9b38653dae4f4ebbd120adba40ac33:
      ansible_host: 192.168.0.28
